package main;
import java.lang.Math;
import javafx.geometry.Point2D;;
public class masterClass {
public static double tLength = 10;	
public static double tHeight = 3;
public static Point2D p0 = new Point2D(0,0);
public static Point2D p1 = new Point2D(5,0);
public static Point2D p2 = new Point2D(tLength,0);
public static Point2D p3 = new Point2D(7,tHeight);
public static Point2D p4 = new Point2D(3,tHeight);
public static String Pp0 = (p0.getX() + " " + p0.getY());
public static String Pp1 = (p1.getX() + " " + p1.getY());
public static String Pp2 = (p2.getX() + " " + p2.getY());
public static String Pp3 = (p3.getX() + " " + p3.getY());
public static String Pp4 = (p4.getX() + " " + p4.getY());
public static Point2D trigP0 = new Point2D(p4.getX(),0);
public static Point2D trigP1 = new Point2D(p3.getX(),0);
public static Point2D trigP2 = new Point2D(p2.getX(),tHeight);
public static double angleDAB;
public static double angleADB;
public static double angleDBA;
public static double angleEDB;
public static double angleDBE;
public static double angleDEB;
public static double angleBEC;
public static double angleECB;
public static double angleCBE;
public static double force4 = 1000;
public static double forceD4 = 3;
public static double force3 = 500;
public static double forceD3 = 3;
public static double force1 = 200;
public static double forceD1 = 3;
public static double sAD;
public static double sDB;
public static double sEB;
public static double sEC;
public static double fSECX = 0;
public static double fSEDX = 0;
public static double fSABX = 0;
public static double fSBCX = 0;
public static double fSDBX = 0;
public static double fSADX = 0;
public static double fSEBX = 0;
public static double fSECY;
public static double fSEDY;
public static double fSABY;
public static double fSBCY;
public static double fSDBY;
public static double fSADY;
public static double fSEBY;
public static double eqX = 0;
public static double eqY = 0;
public static boolean isMovingX = false;
public static boolean isMovingY = false;
public static double fToCancel;
public static double forceA;
public static double forceC;
public static double forceD0 = 1;
public static double forceD2 = 1;
public static double eqYT;
	public static void main(String[] args) {
		sAD = Math.sqrt(Math.pow(trigP0.getX(), 2) + Math.pow(tHeight, 2));
		sDB = Math.sqrt(Math.pow(p1.getX() - trigP0.getX(), 2) + Math.pow(tHeight, 2));
		sEB = Math.sqrt(Math.pow(trigP1.getX() - trigP2.getX(), 2) + Math.pow(tHeight, 2));
		sEC = Math.sqrt(Math.pow(p2.getX() - trigP2.getX(), 2) + Math.pow(tHeight, 3));
		angleDAB = Math.asin(tHeight/sAD);
		angleDBA = Math.asin(tHeight/sDB);
		angleADB = 180 - (Math.toDegrees(angleDAB) + Math.toDegrees(angleDBA));
		angleADB = Math.toRadians(angleADB);
		angleECB = angleDAB;
		angleBEC = angleADB;
		angleCBE = angleDBA;
		angleDBE = 180 - (Math.toDegrees(angleDBA) + Math.toDegrees(angleCBE));
		angleDBE = Math.toRadians(angleDBE);
		angleDEB = 90 - (.5*Math.toDegrees(angleDBE));
		angleDEB = Math.toRadians(angleDEB);
		angleEDB = angleDEB;
		if(forceD4 == 3 || 1 == forceD4){eqY = force4 + eqY;}
		if(forceD3 == 3 || 1 == forceD3){eqY = force3 + eqY;}
		if(forceD1 == 3 || 1 == forceD1){eqY = force1 + eqY;}
		forceA = (force1*p1.getX()) + (force3*p3.getX()) +  (force4*p4.getX());
		forceA = -(forceA)/10;
		forceC = (force4*Math.abs(p4.getX()-tLength)) + (force1*Math.abs(p1.getX()-tLength) + (force3*Math.abs(p3.getX()-tLength)));
		forceC = -(forceC)/10;
		fSADY = (forceA)/Math.sin(angleDAB);
		fSABY = (-fSADY)*Math.cos(angleDAB);
		fSECY = (forceC)/Math.sin(angleECB);
		fSBCY= (-fSECY)*Math.cos(angleECB);
		fSDBY = fSADY/Math.sin(angleDBA);
		fSEBY = fSECY/Math.sin(angleCBE);
		double fSEDYT = (fSADY + fSABY + fSECY + fSBCY + fSDBY + fSEBY);
		fSEDY = 0 - fSEDYT;
		System.out.println("Total length is: " + tLength);
		System.out.println("Total height is: " + tHeight);
		System.out.println("sum of downward Y force is: " + eqY);
		System.out.println("sum of upward Y force is: " + -eqY);
		System.out.println("sum of all X force is: " + eqX);
		System.out.println("Measure of angle DAB: " + Math.toDegrees(angleDAB));
		System.out.println("Measure of angle DBA: " + Math.toDegrees(angleDBA));
		System.out.println("Measure of angle ADB: " + Math.toDegrees(angleADB));
		System.out.println("Measure of angle ECB: " + Math.toDegrees(angleECB));
		System.out.println("Measure of angle BEC: " + Math.toDegrees(angleBEC));
		System.out.println("Measure of angle DEB: " + Math.toDegrees(angleDEB));
		System.out.println("Measure of angle DBE: " + Math.toDegrees(angleDBE));
		System.out.println("Measure of angle EDB: " + Math.toDegrees(angleEDB));
		System.out.println("Measure of angle CBE: " + Math.toDegrees(angleCBE));
		System.out.println("Force on point A: " + forceA);
		System.out.println("Force on point C: " + forceC);
		System.out.println("Force on member AD: " + fSADY);
		System.out.println("Force on member AB: " + fSABY);
		System.out.println("force on member EC: " + fSECY);
		System.out.println("Force on member BC: " + fSBCY);
		System.out.println("Force on member DB: " + fSDBY);
		System.out.println("Force on member EB: " + fSEBY);
		System.out.println("Force on member ED: " + fSEDY);
	}

}
